### PR TITLE
Don't prematurely set hot middleware body/headers

### LINKED ISSUE #23: `Content-Type:application/octet-stream` being set for subsequent middleware
Already mentioned in #15 (and leecade/koa-webpack-middleware#23), but I thought I'd open a new issue.

`Content-Type:application/octet-stream` is being set for any middleware hit after this one. Besides being generally incorrect if you're trying to respond with html/text/json, it causes the browser (Chrome at least) to prompt for a download. Working around it means manually setting `ctx.type` to something more appropriate, or else making sure the webpack middleware only gets called on a route where it won't be a problem.

This behaviour is a symptom of `context.body` being unconditionally set to a stream (the passthrough) in the hot middleware part [here](https://github.com/shellscape/koa-webpack/blob/eba327e1d6aaf1e3f128e33bcbbeb28077a1a3b0/index.js#L52). As soon as `context.body` gets assigned, Koa sets the appropriate content type, which then remains even after later reassigning `body` to a string or whatever.

Side note: `writeHead` should be setting `context.status`, not `context.state`, it should look like this:

```js
writeHead: (status, headers) => {
  context.status = status;
  context.set(headers);
}
```
But the method that has been used to hook-in seems a bit hacky and brittle in general to me. I'll see if I can find the time to put together a PR, just wanted to raise this issue while it's in my head.

Thanks for creating this repo by the way, the other one isn't maintained very well 😛

### PR DESCRIPTION
**Pull request by noinkling**
Fixes #23 with minimal changes.

In the [original middleware](https://github.com/glenjamin/webpack-hot-middleware/blob/master/middleware.js) `writeHead` is the first method called on the response object, so I moved the body assignment into there. This way it only gets set after the path check succeeds.

I also took the opportunity to fix the erroneous `context.state` assignment (I'm sure people wouldn't appreciate that being overwritten).

Did a couple of manual tests and it seems to work fine.

### CODE REVIEW

**Comment by shellscape** [comment]
thanks for this. apologies that it took so long to get eyes on it, it's been a little nutty lately on my end.

File: dist/index.js [hunk 1]
```diff
@@ -124,19 +124,17 @@ function koaHotware(compiler, options) {
           switch (_context2.prev = _context2.next) {
             case 0:
               stream = new _stream.PassThrough();
-
```
Comment (shellscape) [inline dist/index.js]: in the future please don't commit the `dist` directory. won't let that block this PR this time around.
